### PR TITLE
Update Default PHP version

### PR DESCRIPTION
**Pull request by shkkmo**
This change lets this role play nice with the default variable introduced to ansible-role-php introduced in this commit: https://github.com/geerlingguy/ansible-role-php/commit/809394707981f10232e58cac6a607e2a5d016a5b

### CODE REVIEW

**Comment by shkkmo** [comment]
this is still awaiting a merge, should be pretty simple and doesn't need to be marked stale.

**Comment by shkkmo** [comment]
Just a one line fix I still think this is easily mergeable.

**Comment by geerlingguy** [comment]
Yeah this does need fixing!

**Comment by geerlingguy** [comment]
Thanks!

**Pull request merged**
